import asyncio
import logging
import os
from datetime import datetime, timedelta, timezone

from aiohttp import web
from aiogram import Bot, Dispatcher, F, Router
from aiogram.client.default import DefaultBotProperties
from aiogram.enums import ParseMode, ContentType
from aiogram.exceptions import TelegramAPIError
from aiogram.filters import Command
from aiogram.types import Message
from aiogram.webhook.aiohttp_server import SimpleRequestHandler, setup_application

from sqlalchemy import BigInteger, DateTime, Integer, select
from sqlalchemy.ext.asyncio import (
    AsyncSession,
    async_sessionmaker,
    create_async_engine,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


# ============================================================
# ADS (12 messages, round-robin)
# ============================================================

ADS = [
    """🌌 Somewhere between reality and imagination...

A place where faces are generated by AI.

A place where entire planets are born from algorithms.

A place where cinematic scenes exist only because artificial intelligence created them.

Welcome to Mythic AI Store.

🎨 Premium AI Images

🎬 Cinematic AI Videos

⚡ Instant Delivery

💎 Crypto Payments

🎁 Free Demo Available

👉 @mythic_ai_store_bot""",

    """👀 What you're about to see wasn't created by a camera.

Every face.

Every planet.

Every scene.

Generated by AI.

Explore exclusive collections of premium AI content:

👤 Face Pack

❤️ Love Pack

🪐 Planets Pack

🎬 Cinematic Video Packs

🚀 Start exploring:

@mythic_ai_store_bot""",

    """🤖 Artificial Intelligence is creating things that were impossible just a few years ago.

Now you can access a curated collection of AI-generated artwork and cinematic videos in one place.

✨ HD Quality

✨ Unique Content

✨ Instant Delivery

🎁 Free Demo Available

🌌 Mythic AI Store

👉 @mythic_ai_store_bot""",

    """🔥 Not stock photos.

🔥 Not copied content.

🔥 Not ordinary visuals.

Only premium AI-generated creations.

👤 Realistic Faces

❤️ Romantic Scenes

🪐 Amazing Planetary Worlds

🎬 Cinematic AI Videos

Experience what AI can create.

👉 @mythic_ai_store_bot""",

    """🌠 Explore worlds that never existed.

Meet people who were never born.

Watch scenes that were never filmed.

Everything inside Mythic AI Store is generated using artificial intelligence.

🎨 HD AI Image Packs

🎬 Cinematic AI Video Collections

⚡ Instant Delivery

🎁 Free Demo

@mythic_ai_store_bot""",

    """🚀 Welcome to the AI Generation.

A new era where creativity has no limits.

Inside Mythic AI Store:

👤 Ultra-Realistic AI Faces

❤️ Beautiful Romantic Art

🪐 Incredible Space Worlds

🎬 Cinematic Video Packs

💎 Secure Crypto Payments

⚡ Instant Access

🎁 Free Demo

Start your journey:

@mythic_ai_store_bot""",

    """💭 Imagine having access to content that almost nobody else has.

Unique AI-generated images.

Exclusive cinematic videos.

Premium quality.

That's exactly what Mythic AI Store offers.

🎁 Try a free demo today.

👉 @mythic_ai_store_bot""",

    """🌍 The future isn't coming.

It's already here.

Artificial intelligence is creating stunning visuals, cinematic videos, and entire digital worlds.

Explore them today in Mythic AI Store.

🎁 Free Demo Available

🚀 @mythic_ai_store_bot""",

    """🎬 Every frame tells a story.

🪐 Every planet hides a mystery.

👤 Every face feels real.

But none of them actually exist.

Discover premium AI-generated content at:

🌌 @mythic_ai_store_bot

🎁 Free Demo Available

⚡ Instant Delivery

💎 Crypto Payments""",

    """🌟 Step Into The Future Of Creativity

Mythic AI Store brings together some of the most impressive AI-generated images and videos in one place.

🖼 HD AI Images

🎬 Cinematic Video Packs

💎 Crypto Payments

⚡ Instant Delivery

Thousands of details.

Unlimited imagination.

🎁 Free Demo Available.

Join today:

@mythic_ai_store_bot""",

    """🔥 AI HAS NO LIMITS 🔥

Explore a growing collection of premium AI-generated content.

🌌 Alien Worlds

👤 Realistic Portraits

❤️ Emotional Artwork

🎬 Cinematic Videos

All available in high quality with instant delivery.

🎁 Try a free demo before buying.

Start exploring now:

@mythic_ai_store_bot""",

    """🚀 PREMIUM AI CONTENT STORE

Looking for high-quality AI-generated images and videos?

Mythic AI Store offers exclusive collections featuring:

🎨 100 HD Images Per Pack

🎬 Cinematic AI Videos

👤 Realistic Faces

❤️ Love & Romance Themes

🪐 Space & Planetary Art

✔ Instant Access

✔ Secure Payments

✔ Free Demo

✔ Premium Quality

Join now and explore the next generation of digital content.

👉 @mythic_ai_store_bot""",

    """🤯 These people don't exist.

🪐 These planets don't exist.

🎬 These scenes were never filmed.

Everything was created by AI.

Discover premium collections of:

👤 Hyper-Realistic Faces

❤️ Romantic AI Art

🪐 Space & Planet Worlds

🎬 Cinematic AI Videos

🎁 Free Demo Available

⚡ Instant Delivery

💎 Crypto Payments Accepted

See what modern AI is capable of.

🚀 Start Here:

@mythic_ai_store_bot""",

    """🌌 Welcome to Mythic AI Store 🌌

A premium marketplace for AI-generated images and cinematic videos.

Inside you'll discover:

👤 Realistic AI Face Collections

❤️ Beautiful Love & Romance Artwork

🪐 Stunning Planetary Worlds

🎬 Cinematic AI Video Packs

Why join?

✨ HD Quality Content

⚡ Instant Delivery

💎 Secure Crypto Payments

🎁 Free Daily Demos

🚀 Exclusive AI Creations

Whether you're an AI enthusiast, content creator, or simply curious about the power of artificial intelligence, Mythic AI Store offers unique content you won't find anywhere else.

👉 @mythic_ai_store_bot

Experience the future of digital creativity today."""
]

current_ad_index = 0


# ============================================================
# CONFIG
# ============================================================

BOT_TOKEN = os.getenv("BOT_TOKEN", "").strip()
DATABASE_URL = os.getenv("DATABASE_URL", "").strip()

PUBLIC_URL = os.getenv("PUBLIC_URL", "").strip()
WEBHOOK_URL = os.getenv("WEBHOOK_URL", "").strip()
WEBHOOK_PATH = os.getenv("WEBHOOK_PATH", "/webhook").strip()
WEBHOOK_SECRET = os.getenv("WEBHOOK_SECRET", "").strip()

PORT = int(os.getenv("PORT", "8080"))

MIN_MESSAGES = int(os.getenv("MIN_MESSAGES", "5"))
MIN_INTERVAL_SECONDS = int(os.getenv("MIN_INTERVAL_SECONDS", "3600"))
CHECK_INTERVAL_SECONDS = int(os.getenv("CHECK_INTERVAL_SECONDS", "15"))

if not BOT_TOKEN:
    raise RuntimeError("BOT_TOKEN is missing")

if not DATABASE_URL:
    raise RuntimeError("DATABASE_URL is missing")

if not WEBHOOK_URL:
    if not PUBLIC_URL:
        raise RuntimeError("Set either WEBHOOK_URL or PUBLIC_URL")
    WEBHOOK_URL = PUBLIC_URL.rstrip("/") + WEBHOOK_PATH

if DATABASE_URL.startswith("postgres://"):
    DATABASE_URL = DATABASE_URL.replace("postgres://", "postgresql+asyncpg://", 1)
elif DATABASE_URL.startswith("postgresql://") and "+asyncpg" not in DATABASE_URL:
    DATABASE_URL = DATABASE_URL.replace("postgresql://", "postgresql+asyncpg://", 1)

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("ad-bot")


# ============================================================
# DATABASE
# ============================================================

class Base(DeclarativeBase):
    pass


class GroupState(Base):
    __tablename__ = "group_state"

    chat_id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    message_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    last_ad_time: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )


engine = create_async_engine(DATABASE_URL, echo=False, pool_pre_ping=True)
SessionLocal = async_sessionmaker(engine, expire_on_commit=False, class_=AsyncSession)


# ============================================================
# TELEGRAM
# ============================================================

bot = Bot(
    BOT_TOKEN,
    default=DefaultBotProperties(parse_mode=ParseMode.HTML),
)

dp = Dispatcher()
router = Router()
dp.include_router(router)

send_lock = asyncio.Lock()
checker_task: asyncio.Task | None = None


def utcnow() -> datetime:
    return datetime.now(timezone.utc)


def is_service_message(message: Message) -> bool:
    return any(
        [
            bool(message.group_chat_created),
            bool(message.supergroup_chat_created),
            bool(message.channel_chat_created),
            bool(message.new_chat_members),
            bool(message.left_chat_member),
            message.migrate_to_chat_id is not None,
            message.migrate_from_chat_id is not None,
            message.pinned_message is not None,
        ]
    )


async def init_db() -> None:
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)
    logger.info("Database tables are ready")


async def get_or_create_group_state(session: AsyncSession, chat_id: int) -> GroupState:
    state = await session.get(GroupState, chat_id)
    if state is None:
        state = GroupState(
            chat_id=chat_id,
            message_count=0,
            last_ad_time=None,
            created_at=utcnow(),
            updated_at=utcnow(),
        )
        session.add(state)
        await session.flush()
        logger.info("Created new group_state row for chat_id=%s", chat_id)
    return state


def ad_is_due(state: GroupState) -> bool:
    if state.message_count < MIN_MESSAGES:
        return False

    if state.last_ad_time is None:
        return True

    elapsed = utcnow() - state.last_ad_time
    return elapsed >= timedelta(seconds=MIN_INTERVAL_SECONDS)


def get_next_ad_text() -> str:
    global current_ad_index

    ad_text = ADS[current_ad_index]
    current_ad_index += 1

    if current_ad_index >= len(ADS):
        current_ad_index = 0

    return ad_text


async def try_send_ad_for_chat(chat_id: int) -> bool:
    async with send_lock:
        async with SessionLocal() as session:
            state = await session.get(GroupState, chat_id)

            if state is None:
                logger.warning("No DB row found for chat_id=%s", chat_id)
                return False

            if not ad_is_due(state):
                return False

            ad_text = get_next_ad_text()

            try:
                await bot.send_message(
                    chat_id=chat_id,
                    text=ad_text,
                    disable_web_page_preview=False,
                )
            except TelegramAPIError:
                logger.exception("Telegram API error while sending ad to chat_id=%s", chat_id)
                return False
            except Exception:
                logger.exception("Unexpected error while sending ad to chat_id=%s", chat_id)
                return False

            state.message_count = 0
            state.last_ad_time = utcnow()
            state.updated_at = utcnow()
            await session.commit()

            logger.info("Ad sent successfully to chat_id=%s", chat_id)
            return True


async def periodic_checker() -> None:
    while True:
        try:
            async with SessionLocal() as session:
                result = await session.execute(select(GroupState.chat_id))
                chat_ids = [row[0] for row in result.all()]

            for chat_id in chat_ids:
                await try_send_ad_for_chat(chat_id)

        except asyncio.CancelledError:
            raise
        except Exception:
            logger.exception("Periodic checker failed")

        await asyncio.sleep(CHECK_INTERVAL_SECONDS)


# ============================================================
# HANDLERS
# ============================================================

@router.message(Command("start"))
async def start_handler(message: Message) -> None:
    await message.answer("ربات فعال است.")


@router.message(Command("status"))
async def status_handler(message: Message) -> None:
    async with SessionLocal() as session:
        state = await session.get(GroupState, message.chat.id)

    if state is None:
        await message.answer("برای این گروه هنوز رکوردی در دیتابیس نیست.")
        return

    last_ad_text = "None" if state.last_ad_time is None else state.last_ad_time.isoformat()

    await message.answer(
        f"chat_id: <code>{state.chat_id}</code>\n"
        f"message_count: <code>{state.message_count}</code>\n"
        f"last_ad_time: <code>{last_ad_text}</code>\n"
        f"current_ad_index: <code>{current_ad_index}</code>"
    )


@router.message(F.chat.type.in_({"group", "supergroup"}))
async def group_message_handler(message: Message) -> None:
    if not message.from_user:
        return

    if message.from_user.is_bot:
        return

    if is_service_message(message):
        return

    logger.info(
        "Message received: chat=%s user=%s type=%s",
        message.chat.id,
        message.from_user.id,
        message.content_type,
    )

    async with SessionLocal() as session:
        state = await get_or_create_group_state(session, message.chat.id)
        state.message_count += 1
        state.updated_at = utcnow()
        await session.commit()

    await try_send_ad_for_chat(message.chat.id)


# ============================================================
# STARTUP / SHUTDOWN
# ============================================================

async def on_startup(app: web.Application) -> None:
    global checker_task

    await init_db()

    await bot.set_webhook(
        url=WEBHOOK_URL,
        secret_token=WEBHOOK_SECRET or None,
        drop_pending_updates=True,
    )
    logger.info("Webhook set to: %s", WEBHOOK_URL)

    checker_task = asyncio.create_task(periodic_checker())
    app["checker_task"] = checker_task


async def on_shutdown(app: web.Application) -> None:
    task = app.get("checker_task")
    if task:
        task.cancel()
        try:
            await task
        except asyncio.CancelledError:
            pass

    try:
        await bot.delete_webhook(drop_pending_updates=False)
    except Exception:
        logger.exception("Failed to delete webhook on shutdown")

    await bot.session.close()
    await engine.dispose()


# ============================================================
# APP
# ============================================================

def main() -> None:
    app = web.Application()

    SimpleRequestHandler(
        dispatcher=dp,
        bot=bot,
        secret_token=WEBHOOK_SECRET or None,
    ).register(app, path=WEBHOOK_PATH)

    setup_application(app, dp, bot=bot)

    app.on_startup.append(on_startup)
    app.on_shutdown.append(on_shutdown)

    web.run_app(app, host="0.0.0.0", port=PORT)


if __name__ == "__main__":
    main()
