import asyncio
import logging
import os
from datetime import datetime, timedelta, timezone

from aiohttp import web
from aiogram import Bot, Dispatcher, F, Router
from aiogram.client.default import DefaultBotProperties
from aiogram.enums import ParseMode, ContentType
from aiogram.exceptions import TelegramAPIError
from aiogram.filters import Command
from aiogram.types import Message
from aiogram.webhook.aiohttp_server import SimpleRequestHandler, setup_application

from sqlalchemy import BigInteger, DateTime, Integer, select
from sqlalchemy.ext.asyncio import (
    AsyncSession,
    async_sessionmaker,
    create_async_engine,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


# ============================================================
# ADS (12 messages, round-robin)
# ============================================================

ADS = [
    """🤯 These images don't exist.

Every face, every planet, every scene was generated entirely by AI.

Inside Mythic AI Store you'll find:

👤 Realistic AI Faces
❤️ Beautiful Romantic Artwork
🪐 Breathtaking Planetary Worlds
🎬 Cinematic AI Videos

All in HD quality and delivered instantly.

🎁 Free demo available.

See what AI can create.""",

    """🚀 The future of digital art is already here.

Why spend hours searching for content when you can access premium AI-generated collections in seconds?

✔ 100 HD images per pack
✔ Cinematic AI videos
✔ Instant delivery
✔ Secure crypto payments

🎁 Try a free demo and judge the quality yourself.

Welcome to Mythic AI Store.""",

    """🌌 What if entire worlds could be created with a single prompt?

Explore stunning AI-generated planets, realistic faces, romantic artwork, and cinematic videos.

Thousands of unique visuals.
One marketplace.

💎 Premium AI Content
⚡ Instant Access
🎁 Free Demo Available

Mythic AI Store.""",

    """⚠️ Warning:

You may spend hours browsing these collections.

From hyper-realistic faces to beautiful space worlds and cinematic AI videos, every pack is designed to showcase what modern AI can do.

🎨 HD Quality
🎬 Cinematic Visuals
⚡ Instant Delivery
💎 Crypto Payments

🎁 Grab a free demo today.""",

    """🔥 Over 100 AI-generated images in every pack.

No stock photos.
No recycled content.

Just unique AI creations ready for creators, designers, and AI enthusiasts.

👤 Face Pack
❤️ Love Pack
🪐 Planets Pack
🎬 Video Collections

🎁 Free demo available now.""",

    """👀 Looking for something different?

Most content online looks the same.

Mythic AI Store offers exclusive AI-generated images and cinematic videos that stand out immediately.

✨ Unique
✨ High Quality
✨ Instant Delivery

🎁 Start with a free demo.""",

    """🌟 AI is changing content creation forever.

Discover premium collections of images and videos generated by advanced AI systems.

🖼 HD Images
🎬 Cinematic Videos
⚡ Instant Delivery
💎 Crypto Payments

Experience the next generation of creativity.

🎁 Free Demo Included.""",

    """💭 Ever wondered what unlimited imagination looks like?

Explore collections filled with realistic faces, emotional artwork, alien worlds, and cinematic AI videos.

Every item is generated by AI.
Every collection is unique.

🌌 Mythic AI Store
🎁 Free Demo Available""",

    """🌌 Welcome to Mythic AI Store 🌌

Discover a premium collection of AI-generated images and cinematic videos designed for creators, marketers, social media pages, and AI enthusiasts.

✨ What You'll Find:

🎨 HD AI Image Packs
👤 Realistic Human Faces
❤️ Romantic & Emotional Artwork
🪐 Stunning Planetary Worlds

🎬 Cinematic AI Video Packs
🌌 Beautiful Visual Effects
🎥 High-Quality AI Animations
⚡ Ready for Instant Download

Why Choose Mythic AI Store?

✅ Premium Quality Content
✅ Affordable Pricing
✅ Instant Delivery After Payment
✅ Secure Crypto Payments
✅ Exclusive Collections

Not sure if it's worth it?

🎁 Claim a free demo and experience the quality yourself before making a purchase.

The future of digital content is powered by AI. Join today and unlock a growing library of unique creations.""",

    """🔥 PREMIUM AI CONTENT FOR CREATORS 🔥

Are you searching for unique images and videos that stand out from the crowd?

Mythic AI Store offers carefully selected AI-generated content packs created for people who want something different.

Inside our collections you'll discover:

🎨 100 HD AI Images per Pack
👤 Hyper-realistic AI Faces
❤️ Beautiful Romantic Scenes
🪐 Incredible Space and Planet Artwork

Plus:

🎬 Professional Cinematic AI Videos
✨ High-Definition Quality
⚡ Instant Access After Payment

Whether you're creating content for Telegram, Instagram, YouTube, websites, advertisements, or personal projects, our collections can help you save time and elevate your work.

💎 Secure cryptocurrency payments.
🎁 Free demo available.
🚀 Instant delivery.

Join Mythic AI Store and experience the next generation of digital creativity.""",

    """🚀 STEP INTO THE WORLD OF AI-GENERATED ART

Welcome to Mythic AI Store, your destination for premium AI-generated content.

Our collections include hundreds of professionally generated images and cinematic videos designed to inspire, entertain, and enhance your projects.

Available Packs:

👤 Face Pack
A collection of realistic AI-generated portraits with impressive detail and quality.

❤️ Love Pack
Romantic, emotional, and visually striking AI artwork perfect for creative projects.

🪐 Planets Pack
Explore breathtaking alien worlds, galaxies, and futuristic planetary landscapes.

🎬 Cinematic Video Collections
Short AI-generated cinematic videos featuring stunning visuals and atmospheric storytelling.

Why Customers Love Mythic AI Store:

✨ HD Resolution
⚡ Instant Delivery
💎 Crypto-Friendly Payments
🎁 Free Demo Access
📦 Exclusive Content Packs

Don't settle for ordinary content.

Discover the power of AI creativity and unlock premium collections today.""",

    """🌟 DISCOVER EXCLUSIVE AI CONTENT 🌟

Thousands of creators are turning to AI-generated media to create eye-catching content, and now you can too.

At Mythic AI Store, you'll find premium collections of AI images and videos crafted to deliver quality, originality, and visual impact.

🎨 High-Resolution Image Packs
🎬 Cinematic AI Videos
⚡ Instant Delivery
💎 Secure Crypto Payments

Featured Themes:

👤 Realistic Faces
❤️ Love & Romance
🪐 Space & Planetary Worlds

Every pack is designed to provide unique visuals that can be used for inspiration, social media content, digital projects, and creative exploration.

🎁 Free Demo Available
🚀 Start Exploring Today

Mythic AI Store — Where Creativity Meets Artificial Intelligence.""",
]

current_ad_index = 0


# ============================================================
# CONFIG
# ============================================================

BOT_TOKEN = os.getenv("BOT_TOKEN", "").strip()
DATABASE_URL = os.getenv("DATABASE_URL", "").strip()

PUBLIC_URL = os.getenv("PUBLIC_URL", "").strip()
WEBHOOK_URL = os.getenv("WEBHOOK_URL", "").strip()
WEBHOOK_PATH = os.getenv("WEBHOOK_PATH", "/webhook").strip()
WEBHOOK_SECRET = os.getenv("WEBHOOK_SECRET", "").strip()

PORT = int(os.getenv("PORT", "8080"))

MIN_MESSAGES = int(os.getenv("MIN_MESSAGES", "5"))
MIN_INTERVAL_SECONDS = int(os.getenv("MIN_INTERVAL_SECONDS", "3600"))
CHECK_INTERVAL_SECONDS = int(os.getenv("CHECK_INTERVAL_SECONDS", "15"))

if not BOT_TOKEN:
    raise RuntimeError("BOT_TOKEN is missing")

if not DATABASE_URL:
    raise RuntimeError("DATABASE_URL is missing")

if not WEBHOOK_URL:
    if not PUBLIC_URL:
        raise RuntimeError("Set either WEBHOOK_URL or PUBLIC_URL")
    WEBHOOK_URL = PUBLIC_URL.rstrip("/") + WEBHOOK_PATH

if DATABASE_URL.startswith("postgres://"):
    DATABASE_URL = DATABASE_URL.replace("postgres://", "postgresql+asyncpg://", 1)
elif DATABASE_URL.startswith("postgresql://") and "+asyncpg" not in DATABASE_URL:
    DATABASE_URL = DATABASE_URL.replace("postgresql://", "postgresql+asyncpg://", 1)

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("ad-bot")


# ============================================================
# DATABASE
# ============================================================

class Base(DeclarativeBase):
    pass


class GroupState(Base):
    __tablename__ = "group_state"

    chat_id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    message_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    last_ad_time: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )


engine = create_async_engine(DATABASE_URL, echo=False, pool_pre_ping=True)
SessionLocal = async_sessionmaker(engine, expire_on_commit=False, class_=AsyncSession)


# ============================================================
# TELEGRAM
# ============================================================

bot = Bot(
    BOT_TOKEN,
    default=DefaultBotProperties(parse_mode=ParseMode.HTML),
)

dp = Dispatcher()
router = Router()
dp.include_router(router)

send_lock = asyncio.Lock()
checker_task: asyncio.Task | None = None


def utcnow() -> datetime:
    return datetime.now(timezone.utc)


def is_service_message(message: Message) -> bool:
    return any(
        [
            bool(message.group_chat_created),
            bool(message.supergroup_chat_created),
            bool(message.channel_chat_created),
            bool(message.new_chat_members),
            bool(message.left_chat_member),
            message.migrate_to_chat_id is not None,
            message.migrate_from_chat_id is not None,
            message.pinned_message is not None,
        ]
    )


async def init_db() -> None:
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)
    logger.info("Database tables are ready")


async def get_or_create_group_state(session: AsyncSession, chat_id: int) -> GroupState:
    state = await session.get(GroupState, chat_id)
    if state is None:
        state = GroupState(
            chat_id=chat_id,
            message_count=0,
            last_ad_time=None,
            created_at=utcnow(),
            updated_at=utcnow(),
        )
        session.add(state)
        await session.flush()
        logger.info("Created new group_state row for chat_id=%s", chat_id)
    return state


def ad_is_due(state: GroupState) -> bool:
    if state.message_count < MIN_MESSAGES:
        return False

    if state.last_ad_time is None:
        return True

    elapsed = utcnow() - state.last_ad_time
    return elapsed >= timedelta(seconds=MIN_INTERVAL_SECONDS)


def get_next_ad_text() -> str:
    global current_ad_index

    ad_text = ADS[current_ad_index]
    current_ad_index += 1

    if current_ad_index >= len(ADS):
        current_ad_index = 0

    return ad_text


async def try_send_ad_for_chat(chat_id: int) -> bool:
    async with send_lock:
        async with SessionLocal() as session:
            state = await session.get(GroupState, chat_id)

            if state is None:
                logger.warning("No DB row found for chat_id=%s", chat_id)
                return False

            if not ad_is_due(state):
                return False

            ad_text = get_next_ad_text()

            try:
                await bot.send_message(
                    chat_id=chat_id,
                    text=ad_text,
                    disable_web_page_preview=False,
                )
            except TelegramAPIError:
                logger.exception("Telegram API error while sending ad to chat_id=%s", chat_id)
                return False
            except Exception:
                logger.exception("Unexpected error while sending ad to chat_id=%s", chat_id)
                return False

            state.message_count = 0
            state.last_ad_time = utcnow()
            state.updated_at = utcnow()
            await session.commit()

            logger.info("Ad sent successfully to chat_id=%s", chat_id)
            return True


async def periodic_checker() -> None:
    while True:
        try:
            async with SessionLocal() as session:
                result = await session.execute(select(GroupState.chat_id))
                chat_ids = [row[0] for row in result.all()]

            for chat_id in chat_ids:
                await try_send_ad_for_chat(chat_id)

        except asyncio.CancelledError:
            raise
        except Exception:
            logger.exception("Periodic checker failed")

        await asyncio.sleep(CHECK_INTERVAL_SECONDS)


# ============================================================
# HANDLERS
# ============================================================

@router.message(Command("start"))
async def start_handler(message: Message) -> None:
    await message.answer("ربات فعال است.")


@router.message(Command("status"))
async def status_handler(message: Message) -> None:
    async with SessionLocal() as session:
        state = await session.get(GroupState, message.chat.id)

    if state is None:
        await message.answer("برای این گروه هنوز رکوردی در دیتابیس نیست.")
        return

    last_ad_text = "None" if state.last_ad_time is None else state.last_ad_time.isoformat()

    await message.answer(
        f"chat_id: <code>{state.chat_id}</code>\n"
        f"message_count: <code>{state.message_count}</code>\n"
        f"last_ad_time: <code>{last_ad_text}</code>\n"
        f"current_ad_index: <code>{current_ad_index}</code>"
    )


@router.message(F.chat.type.in_({"group", "supergroup"}))
async def group_message_handler(message: Message) -> None:
    if not message.from_user:
        return

    if message.from_user.is_bot:
        return

    if is_service_message(message):
        return

    logger.info(
        "Message received: chat=%s user=%s type=%s",
        message.chat.id,
        message.from_user.id,
        message.content_type,
    )

    async with SessionLocal() as session:
        state = await get_or_create_group_state(session, message.chat.id)
        state.message_count += 1
        state.updated_at = utcnow()
        await session.commit()

    await try_send_ad_for_chat(message.chat.id)


# ============================================================
# STARTUP / SHUTDOWN
# ============================================================

async def on_startup(app: web.Application) -> None:
    global checker_task

    await init_db()

    await bot.set_webhook(
        url=WEBHOOK_URL,
        secret_token=WEBHOOK_SECRET or None,
        drop_pending_updates=True,
    )
    logger.info("Webhook set to: %s", WEBHOOK_URL)

    checker_task = asyncio.create_task(periodic_checker())
    app["checker_task"] = checker_task


async def on_shutdown(app: web.Application) -> None:
    task = app.get("checker_task")
    if task:
        task.cancel()
        try:
            await task
        except asyncio.CancelledError:
            pass

    try:
        await bot.delete_webhook(drop_pending_updates=False)
    except Exception:
        logger.exception("Failed to delete webhook on shutdown")

    await bot.session.close()
    await engine.dispose()


# ============================================================
# APP
# ============================================================

def main() -> None:
    app = web.Application()

    SimpleRequestHandler(
        dispatcher=dp,
        bot=bot,
        secret_token=WEBHOOK_SECRET or None,
    ).register(app, path=WEBHOOK_PATH)

    setup_application(app, dp, bot=bot)

    app.on_startup.append(on_startup)
    app.on_shutdown.append(on_shutdown)

    web.run_app(app, host="0.0.0.0", port=PORT)


if __name__ == "__main__":
    main()